baseofstudents/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from students import views


app_name = "students"
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.students, name= 'students'),
    url(r'^parametry/', include('parametry.urls')),
    url(r'^students/add/$', views.students_add, name='students_add'),
    url(r'^students/test/$', views.students_test, name='students_test'),      
    url(r'^students/(?P<stud_id>[0-9]+)/edit/$', views.students_edit, name='students_edit'), 

] 

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

parametry/urls.py
from django.conf.urls import patterns, url
from parametry import views


app_name = 'parametry'
urlpatterns = [
    url(r'^$', views.parametry, name= 'parametry'), 
    url(r'^group/add/$', views.group_add, name='group_add'),
    url(r'^group/(?P<group_id>[0-9]+)/$', views.group_list, name='group_list'),
]   

parametry/models.py
# -*- coding: utf-8 -*-

from django.db import models



class Groupofstudents(models.Model):
	name = models.CharField(max_length=128, unique=True, verbose_name=u'Групи')
	lead = models.OneToOneField('students.Studentsprofile', verbose_name=u'Староста')

	class Meta:
		verbose_name_plural = 'Groupofstudents'

	def __str__(self):
		return self.name  

students/models.py
# -*- coding: utf-8 -*-

from django.db import models
from parametry.models import Groupofstudents


class Studentsprofile(models.Model):
	firstname = models.CharField(max_length= 50, verbose_name=u'Імя')
	lastname = models.CharField(max_length= 50, verbose_name=u'Призвіще')
	middlename = models.CharField(max_length= 50, verbose_name=u'По батькові')
	date_of_birth = models.DateField(verbose_name=u'Дата народження')
	photo = models.ImageField(upload_to='profile_photo', blank=True)
	students_ticket = models.IntegerField(default=0, verbose_name=u'№ Білету')
	group = models.ForeignKey(Groupofstudents, null=True, blank=True, verbose_name=u'Група')


	def __str__(self):
		return self.firstname
 

parametry/forms.py
from django import forms
from .models import Groupofstudents

class GroupofstudentsForm(forms.ModelForm):

	class Meta:
		model = Groupofstudents
		fields = ('name', 'lead',)

students/forms.py
from django import forms
from .models import Studentsprofile

class StudentsForm(forms.ModelForm):

	class Meta:
		model = Studentsprofile
		fields = ('photo', 'firstname', 'lastname', 'middlename', 'date_of_birth', 'students_ticket', 'group',)

parametry/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from parametry.models import Groupofstudents
from students.models import Studentsprofile
from .forms import GroupofstudentsForm


def parametry(request):
	groups = Groupofstudents.objects.all()
	return render(request, 'parametry/index.html', {'groupsall' : groups})

def group_add(request):
	# GET or POST?
	if request.method == "POST":
		form = GroupofstudentsForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('students')
	else:
		form = GroupofstudentsForm()
	return render(request, 'parametry/group_add.html', {'form' : form})

def group_list(request, group_id):
	context_dict = {}
	group = Groupofstudents.objects.get(id=group_id)
	context_dict['group_id'] = group.id
	student = Studentsprofile.objects.filter(group=group)
	context_dict['student'] = student
	context_dict['group'] = group
	return render(request, 'parametry/group_list.html', context_dict)
	

students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from students.models import Studentsprofile
from parametry.models import Groupofstudents
from .forms import StudentsForm
from django.conf import settings

def base(request):
	return render(request, 'base.html')


def students(request):
	students = Studentsprofile.objects.order_by("students_ticket")
	return render(request, 'students/index.html', {'studentsall': students, 'media_base' : settings.MEDIA_URL })
    # class Meta:
    #     ordering = ["name"]	

def students_test(request):
	return render(request, 'students/test.html' )

def students_add(request):
	if request.method == 'POST':
		form = StudentsForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('students')
	else: 
		form = StudentsForm()
	return render(request, 'students/students_add.html', {'form' : form})
	
def students_edit(request, stud_id):
	stud = get_object_or_404(Studentsprofile, id=stud_id)
	if request.method == 'POST':
		form = StudentsForm(request.POST, instance=stud)
		if form.is_valid():
			form.save()
		return redirect('students.views.students')
	else: 
		form = StudentsForm(instance=stud)
	return render(request, 'students/students_add.html', {'form' : form})

 

parametry/templates/group_list.html
{% extends "base.html" %}
{% load staticfiles %} 


{% block content %}
<br/><br/>
<h2>Група {{ group.name }}</h2>
	{% if group %}
		{% if student %}
			<ul>
				{% for stud in student %}
					<li>Студент {{ stud.lastname}}</li>
				{% endfor %}
			</ul>
		{% else %}
			<h2>No Students</h2>
		{% endif %}
	{% else %}
		<h2>Вибачте, немає такоі групи</h2>
	{% endif %}
{% endblock %}

parametry/templates/index1.html
{% extends "base.html" %}
{% load staticfiles %} 


{% block content %}
<hr/><hr/>
	<h3><strong> Список груп:	</strong></h3>
	<hr/>
<p><a class="btn btn-primary btn-lg" href="{% url 'parametry.views.group_add' %}" role="button">Додати групу</a></p>
<table class="table table-striped">
	<thead>
		<tr>
			<th>№</th>
			<th>Назва групи</th>
			<th>Староста</th>
		</tr>
	</thead>
	<tbody>
	{% for group in groupsall %}
		<tr>
			<td>{{group.id}}</td>
			<td><a href="{% url 'group_list' group_id=group.id %}">{{group.name}}</td>
			<td>{{group.lead}}</td>
		</tr>
	</tbody>
	{% endfor %}
</table>
{% endblock %}
 

parametry/templates/parametry/group_add.html
{% extends "base.html" %}
{% load staticfiles %} 

{% block content %}
<hr/><hr/>
<h1>Додати групу:</h1>
<form method="POST">{% csrf_token %}
	{{ form.as_p }}
 <button type="submit" class="save btn btn-default">Зберегти</button>
</form>
{% endblock%}

parametry/templates/parametry/group_list.html
{% extends "base.html" %}
{% load staticfiles %} 


{% block content %}
<br/><br/>
<h2>Група {{ group.name }}</h2>
	{% if group %}
		{% if student %}
			<ul>
				{% for stud in student %}
					<li>Студент {{ stud.lastname}}&nbsp;{{stud.firstname}}</li>
				{% endfor %}
			</ul>
		{% else %}
			<p>Вибачте, немає такого студента</p>
		{% endif %}
	{% else %}
		<h2>Вибачте, немає такоі групи</h2>
	{% endif %}
{% endblock %}

parametry/templates/parametry/index.html
{% extends "base.html" %}
{% load staticfiles %} 


{% block content %}
<br/><br/>
	<h3><strong> Список груп:	</strong></h3>
	<hr/>
<p><a class="btn btn-primary btn-lg" href="{% url 'parametry:group_add' %}" role="button">Додати групу</a></p>
<table class="table table-striped">
	<thead>
		<tr>
			<th>№</th>
			<th>Назва групи</th>
			<th>Староста</th>
		</tr>
	</thead>
	<tbody>
	{% for group in groupsall %}
		<tr>
			<td>{{group.id}}</td>
			<td><a href="{% url 'parametry:group_list' group.id %}">{{group.name}}</td>
			<td>{{group.lead}}</td>
		</tr>
	</tbody>
	{% endfor %}
</table>
<!-- <img src="{{ some_model.some_image_field.url }}" /> -->
{% endblock %}

students/templates/index.html
{% extends "base.html" %}
{% load staticfiles %} 


{% block content %}
<hr/><hr/>
<h3><strong>База студентів:</strong></h3>
	<hr/>
<p><a class="btn btn-primary btn-lg" href="{% url 'students.views.students_add' %}" role="button">Додати студента</a></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>№</th>
      <th>Ім'я</th>
      <th>Призвіще</th>
      <th>Дата народження</th>
      <th>№ Білету</th>
      <th>Група</th>
    </tr>
  </thead>

  <tbody>
    {% for stud in studentsall %}
    <tr>
      <td>{{stud.id}}</td>
      <td>{{stud.firstname}}</td>
      <td>{{stud.lastname}}</td>
      <td>{{stud.date_of_birth}}</td>
      <td>{{stud.students_ticket}}</td>
      <td><a href="#">{{stud.group}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
 
 
{% endblock %}

students/templates/students/index.html
{% extends "base.html" %}
{% load staticfiles %} 


{% block content %}
<br/><br/>
<h3><strong>База студентів:</strong></h3>
	<hr/>
<p><a class="btn btn-primary btn-lg" href="{% url 'students.views.students_add' %}" role="button">Додати студента</a></p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>№</th>
      <th>Фото</th>
      <th>Ім'я</th>
      <th>Призвіще</th>
      <th>Дата народження</th>
      <th>Група</th>      
      <th>№ Білету</th>
      <th>#</th>
    </tr>
  </thead>

  <tbody>
    {% for stud in studentsall %}
    <tr>
      <td>{{stud.id}}</td>
      <td><img src="{{media_base}}{{ stud.photo}}" alt='profile_photo' height="42" width="42" /></td>
      <td>{{stud.firstname}}</td>
      <td>{{stud.lastname}}</td>
      <td>{{stud.date_of_birth}}</td>
      <td><a href="#">{{stud.group}}</td>      
      <td>{{stud.students_ticket}}</td>
      <td><p><a href="{% url 'students.views.students_edit' stud_id=stud.id %}">Edit...</p></td>
    </tr>
    {% endfor %}
  </tbody>
</table>


    

{% endblock %}


 

students/templates/students/students_add.html
{% extends "base.html" %}
{% load staticfiles %} 


{% block content %}
<hr/><hr/>
<h1>Додати студента:</h1>
<form method="POST" class=students-form>{% csrf_token %}
	{{ form.as_p }}
 	<button type="submit" class="save btn btn-default">Зберегти</button>
</form>
{% endblock %}

students/templates/students/test.html
my test

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
{% block head %}
<head>
	<title>Base_of_Students</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
</head>
{% endblock %}

{% block menu %}
<body>
<div class="container">
  <img src="{% static  'img/lid.jpg' %}" alt="picture of group" align="right" width="102" height="90"/> 
  <div class="topright"><h1>Сервіс Обліку Студентів</h1></div>
</div>
	<nav class="navbar navbar-light bg-faded">
<!--   <a class="navbar-brand" href="#">Home</a> -->
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">Студенти<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/parametry/">Групи</a>
    </li>
   </ul>
{% endblock %}

{% block content %}
{% endblock %}
<br/>
<br/>
{% block footer %}
  {% block copyright %}
    <p>Footer</p>
    <p>@2016 Service Accounting Students</p>
  {% endblock %}
{% endblock %}

</body>
</html>